import type { EditorThemeClasses } from 'lexical';

const theme: EditorThemeClasses = {
  root: 'lex-root',
  paragraph: 'lex-p',
  text: {
    bold: 'lex-bold',
    italic: 'lex-italic',
    underline: 'lex-underline',
    strikethrough: 'lex-strikethrough',
    underlineStrikethrough: 'lex-underline-strikethrough',
    code: 'lex-text-code',
  },
  heading: {
    h1: 'lex-h1',
    h2: 'lex-h2',
    h3: 'lex-h3',
    h4: 'lex-h4',
    h5: 'lex-h5',
    h6: 'lex-h6',
  },
  quote: 'lex-quote',
  list: {
    ul: 'lex-ul',
    ol: 'lex-ol',
    listitem: 'lex-li',
    nested: {
      listitem: 'lex-li-nested',
    },
    listitemChecked: 'lex-li-checked',
    listitemUnchecked: 'lex-li-unchecked',
  },
  code: 'lex-code',
  codeHighlight: {
    atrule: 'lex-token-atrule',
    attr: 'lex-token-attr',
    boolean: 'lex-token-boolean',
    builtin: 'lex-token-builtin',
    cdata: 'lex-token-cdata',
    char: 'lex-token-char',
    class: 'lex-token-class',
    'class-name': 'lex-token-class-name',
    comment: 'lex-token-comment',
    constant: 'lex-token-constant',
    deleted: 'lex-token-deleted',
    doctype: 'lex-token-doctype',
    entity: 'lex-token-entity',
    function: 'lex-token-function',
    important: 'lex-token-important',
    inserted: 'lex-token-inserted',
    keyword: 'lex-token-keyword',
    namespace: 'lex-token-namespace',
    number: 'lex-token-number',
    operator: 'lex-token-operator',
    prolog: 'lex-token-prolog',
    property: 'lex-token-property',
    punctuation: 'lex-token-punctuation',
    regex: 'lex-token-regex',
    selector: 'lex-token-selector',
    string: 'lex-token-string',
    symbol: 'lex-token-symbol',
    tag: 'lex-token-tag',
    url: 'lex-token-url',
    variable: 'lex-token-variable',
  },
  link: 'lex-link',
  hashtag: 'lex-hashtag',
  image: 'lex-image',
};

export default theme;
